name: EDGE Seniors
favicon: null
layout_spectrum: 0.19084675912745297
typography_spectrum: 0.9081332269124687
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#e5e6e1'
    - '#018bba'
    - '#d28b89'
    - '#00415d'
  brandStrength: 0.25
  lightness: 0.20217627380043268
  saturation: 0.5
  rhythmicContrast: 0.7037507246714085
purpose: []
